# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('mac', models.CharField(max_length=128)),
                ('os_system', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField()),
                ('modify_time', models.DateTimeField()),
            ],
        ),
    ]
