# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default='', max_length=64, verbose_name='sn码')),
                ('ip', models.CharField(default='', max_length=64, verbose_name='ip地址')),
                ('hostname', models.CharField(default='', max_length=64, verbose_name='主机名字')),
                ('mac', models.CharField(default='', max_length=64, verbose_name='mac地址')),
                ('addr', models.CharField(default='', max_length=64, verbose_name='网卡地址')),
                ('admin', models.CharField(default='', max_length=64, verbose_name='管理员')),
                ('user', models.CharField(default='', max_length=64, verbose_name='用户名')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mem', models.IntegerField(default=0, verbose_name='内存')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '资源表',
                'verbose_name_plural': '资源表',
            },
        ),
    ]
